<?php

namespace App\Models;

use CodeIgniter\Model;

class LPOperasiKatarakModel extends Model
{
    protected $table = 'medrec_lp_operasi_katarak';
    protected $primaryKey = 'id_lp_operasi_katarak';
    protected $useTimestamps = false;
    protected $allowedFields = [
        'nomor_registrasi',
        'no_rm',
        'tanggal_operasi',
        'mata',
        'operator',
        'jam_operasi',
        'lama_operasi',
        'diagnosis',
        'asisten',
        'jenis_operasi',
        'jenis_anastesi',
        'dokter_anastesi',
        'anastesi_retrobulbar',
        'anastesi_peribulber',
        'anastesi_topikal',
        'anastesi_subtenom',
        'anastesi_lidocain_2',
        'anastesi_marcain_05',
        'anastesi_lainnya',
        'peritomi_basis_forniks',
        'peritomi_basis_limbus',
        'lokasi_superonasal',
        'lokasi_superior',
        'lokasi_supertemporal',
        'lokasi_lainnya',
        'lokasi_insisi_kornea',
        'lokasi_insisi_limbus',
        'lokasi_insisi_skelera',
        'lokasi_insisi_skeleratunnel',
        'lokasi_insisi_sideport',
        'ukuran_inisiasi',
        'alat_insisi_jarum',
        'alat_insisi_crescent',
        'alat_insisi_diamond',
        'capsulectomy_canopener',
        'capsulectomy_envelope',
        'capsulectomy_ccc',
        'ekstraksi_lenca_icce',
        'ekstraksi_lenca_ecce',
        'ekstraksi_lenca_sucea',
        'ekstraksi_lenca_phaco',
        'ekstraksi_lenca_cle',
        'ekstraksi_lenca_ai',
        'tindakan_sphincter',
        'tindakan_virektomi',
        'tindakan_jahitan_iris',
        'tindakan_kapsulotomi_post',
        'tindakan_sinechiolyssis',
        'cairan_irigasi_ri',
        'cairan_irigasi_bss',
        'cairan_irigasi_lainnya',
        'fiksasi_bmb',
        'fiksasi_sulkus_siliaris',
        'fiksasi_sklera',
        'penanaman_diputar',
        'penanaman_tidak_diputar',
        'jenis_dilipat',
        'jenis_tidak_dilipat',
        'posisi_vertikal',
        'posisi_horizontal',
        'posisi_miring',
        'cairan_viscoelastik_healon',
        'cairan_viscoelastik_viscoat',
        'cairan_viscoelastik_amvisca',
        'cairan_viscoelastik_healon_5',
        'cairan_viscoelastik_rohtovisc',
        'benang_vicryl_8_0',
        'benang_vicryl_8_0',
        'jumlah_jahitan',
        'prabedah_od',
        'prabedah_os',
        'komplikasi_tidak_ada',
        'komplikasi_ada',
        'komplikasi_prolaps',
        'komplikasi_pendarahan',
        'komplikasi_lainnya',
        'laporan_operasi',
        'terapi_pascabedah',
        'waktu_dibuat',
    ];
}
